name: Deploy Userhelp Docs
on:
  push:
    branches:
      - '3'
      - '2'
      - '1.1'
    paths:
      - 'docs/en/userguide/**'
jobs:
  deploy:
    name: deploy-userhelp-docs
    runs-on: ubuntu-latest
    steps:
      - name: Run build hook
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_HOOK }}
